apiVersion: apps/v1
kind: Deployment
metadata:
  name: droneex
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: droneex
    spec:
      imagePullSecrets:
        - name: droneci-key
      containers:
        - name: droneex
          image: 751087521896.dkr.ecr.us-west-2.amazonaws.com/droneci:DRONE_BUILD_NUMBER
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: droneex


---
apiVersion: v1
kind: Service
metadata:
  name: droneex-service
  labels:
    name: droneex-service
spec:
  ports:
    - port: 2093
      targetPort: 8080
      protocol: TCP
      name: droneport
  selector:
    app: droneex
  type: LoadBalancer
