apiVersion: apps/v1
kind: Deployment
metadata:
  name: droneex
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: droneex
    spec:
      containers:
        - name: droneex
          image: 'sankar31/droneex:1.4'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: droneex


---
apiVersion: v1
kind: Service
metadata:
  name: droneex-service
  labels:
    name: droneex-service
spec:
  ports:
    - port: 2093
      targetPort: 8080
      protocol: TCP
      name: droneport
  selector:
    app: droneex
  type: LoadBalancer
